### ISSUE TITLE
Lights are not responding to On/Off instructions

### ISSUE THREAD

**Issue by kellydarren** [jjensn/MiThings#21]
Jared

The lights stopped working for me yesterday.  Got around to checking out the logs today, this is what I;m seeing?

80ae3714-7f86-46d2-979d-aa4d3b9caca9  21:48:02: error error: java.lang.SecurityException: Endpoint http://api.mithings.pw/v1/ is blacklisted.
80ae3714-7f86-46d2-979d-aa4d3b9caca9  21:48:02: debug MiLight device: AC:CF:23:53:D3:AA, built path: rgbw/power/off/3

Darren

**Comment by jared-jensen** [comment]
I think you're using the dev environment, which is being upgraded. Will have to use the old endpoint (lights.cloudsy.com)

**Comment by peeepers** [comment]
Hey are the lights working

**Comment by kellydarren** [comment]
Working now

**Comment by kellydarren** [comment]
Nope they aint working.  See below for log info.

I assume that was you setting up disco lights last nite.  I thought it was
pretty cool :-)


80ae3714-7f86-46d2-979d-aa4d3b9caca9
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#80ae3714-7f86-46d2-979d-aa4d3b9caca9>
 16:59:44: error error: java.net.SocketTimeoutException: Read timed out
80ae3714-7f86-46d2-979d-aa4d3b9caca9
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#80ae3714-7f86-46d2-979d-aa4d3b9caca9>
 16:59:34: debug MiLight device: AC:CF:23:53:D3:8E, built path:
rgbw/power/on/2
a9a61a99-5cb1-4405-ab36-ea914c68f960
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#a9a61a99-5cb1-4405-ab36-ea914c68f960>
 16:59:34: debug Zone switch changed state! on!
80ae3714-7f86-46d2-979d-aa4d3b9caca9
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#80ae3714-7f86-46d2-979d-aa4d3b9caca9>
 16:59:37: error error: java.net.SocketTimeoutException: Read timed out
80ae3714-7f86-46d2-979d-aa4d3b9caca9
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#80ae3714-7f86-46d2-979d-aa4d3b9caca9>
 16:59:27: debug MiLight device: AC:CF:23:53:D3:8E, built path:
rgbw/power/off/2
a9a61a99-5cb1-4405-ab36-ea914c68f960
<https://graph-eu01-euwest1.api.smartthings.com/ide/logs#a9a61a99-5cb1-4405-ab36-ea914c68f960>
 16:59:27: debug Zone switch changed state! off!

**Comment by peeepers** [comment]
Nope, I didn't set any lights...that would be a misplacement of trust!

Anyway, looks like you didn't see the latest news / complete the upgrade. The SmartApp endpoint changed

**Comment by peeepers** [comment]
https://github.com/peeepers/MiThings/blob/master/README.md

**Comment by kellydarren** [comment]
Updated my end point.  All good now.

**Comment by jjensn** [comment]
Before you submit an issue, just an FYI I reached my 150$ cap in the cloud and my services were shutdown. Will be up sometime next week.
