### ISSUE TITLE
MiLight Controller Stopped Working

### ISSUE THREAD

**Issue by wilddoghogg** [jjensn/MiThings#22]
Hi Jared,

My MiLights stopped working and started flashing in random colours. I have now updated the hubs to reflect the new address, as well as updating the URI as per your notes. I have republished the app and am now getting the below, any ideas?:-

6:27:50 PM: error error: java.net.SocketTimeoutException: Read timed out
bd4dfa5b-f603-4b4c-9a3a-bbd785fdfc9b  6:27:40 PM: debug MiLight device: AC:CF:23:50:77:BA, built path: rgbw/power/off/1

**Comment by peeepers** [comment]
Hi,

There was an upgrade, you'll need to update your app endpoint. https://github.com/peeepers/MiThings/blob/master/README.md
