### ISSUE TITLE
Can't Automatically Change Color

### ISSUE THREAD

**Issue by techsa573** [jjensn/MiThings#23]
Hi Jared,

Thanks for all your hard work on the updates this week!  After updating the URLs as per your instructions, everything is working just as it was before the update.

Even before the update though, I've been unable to get any automated color change to work.  I can manually set the color in the device screen in the ST app and automated on/off works, but I've been unable to automatically change the color using any method I've tried.

These are the lights I'm using, the PAR30 version (which I guess may be the problem):  https://www.aliexpress.com/item/2-4G-wireless-Mi-Light-RGBW-RGBWW-dimmable-LED-Bulb-5W-6W-9W-AC85-265V-E14/32666838437.html
And this is the wifi controller I have:  https://www.aliexpress.com/item/Mi-Light-Brand-Wifi-Controller-Mini-Ivory-Color-Wireless-Wi-fi-iOS-Android-Led-Remote-Contol/32580106192.html

Is this version of the MiLight one you've been able to confirm is supported, or is it one of the newer versions you mentioned in the ST Forum that you don't have available to test?  If it's the later, I'd be glad to order one for you if you're interested in checking it out.

I've also tried several methods of changing the light color, including the Smart Lighting "Turn on and Set Color" option and CoRE with each of the three color set options (Color, RGB, and HSL).  I've attached a snippet from the ST Live Logging for a test with CoRE and the Color option.  I can retest the other options and provide logs for those as well if that would help.

Just let me know if this is something you're interested in tackling, otherwise I may just pick up a couple of the A19-size bulbs and give those a try in the recessed cans fixtures I'm using instead.

Thanks!

[MiLightColorChange_CoRE_Color_Logging_2016-10-22.txt](https://github.com/peeepers/MiThings/files/545963/MiLightColorChange_CoRE_Color_Logging_2016-10-22.txt)

**Comment by peeepers** [comment]
It's not the bulbs, it's how SmartThings is sending the color data to the device. I think they're sending like "red" or "blue", which isn't a hex code. It's something that I've got to tackle once I find time to sit down and figure out what they're doing on that side.

**Comment by techsa573** [comment]
Gotcha.  Thanks for the feedback!  Just let me know if you need any assistance with testing or validation whenever you get to that point.  I'd be glad to help in any way I can.
