### ISSUE TITLE
Cloud Cap - Cheers for update

### ISSUE THREAD

**Issue by kellydarren** [jjensn/MiThings#25]
Thanks for the update Jared.
Is that cause of all of us using your service or in addition to other work you were doing?

**Comment by jjensn** [comment]
Won't know till everything gets unlocked next week!

**Comment by kellydarren** [comment]
lucky you had the cap so :-)

**Comment by shayden88** [comment]
Is this why my milights have not been working through smartthings app?  I was going through all sorts of troubleshooting the past couple of days trying to figure out what went wrong.

**Comment by jjensn** [comment]
Yes

**Comment by shayden88** [comment]
Well thanks for the update!  I have a lot of mi-lights in my house and am super thankful you put this app together.  Hopefully the cloud data issue gets worked out, wonder if your app has just gotten too popular haha.

**Comment by jjensn** [comment]
Cheers thanks for the good words. You'll have to use the native app and 
maybe even that remote for a few more days until I get it ironed out.

**Comment by kellydarren** [comment]
ahh jared, you used the remote word, shivers I feel shivers :-)

**Comment by jg506** [comment]
jared - thanks so much for contributing your time, and -- I never realized till now -- your own money to the community.  Any chance you will release the cloud backend as opensource too? A lot of us running some form of home server, on Pi or or NAS or what's not to overcome the limitations of ST hub or for other reasons (e.g. homebridge). I think some time ago you mentioned that you dockerised your cloud server. Is it available on docker hub?

**Comment by jjensn** [comment]
everyone keeps asking for me to open source my stuff, yet I have not had a single pull request for my project or seen any evidence that they themselves have open sourced something.

**Comment by jg506** [comment]
Can't argue with you on that. It is frustrating when it is only one way. 
I don't code but if you ever to release the server side I can contribute in creating a readme for setting it up  similarity to how homebridge is documented.

**Comment by jjensn** [comment]
I know, I'm not unloading on you. Service has been down like 3 days now and I keep getting e-mails to my work e-mail about it, since it's on my GH page. 

If it's any consolidation, I built it to run in the cloud. It can scale almost unlimited. People have problems getting the SmartApp installed -- imagine the work I'd be committing to trying to get people how to run docker, redis, load balancers, ruby on rails ... it's just not feasable.

**Comment by jg506** [comment]
I hear ya, IMO, you are already taking too much on yourself running a cloud service and worrying for it to be up. I did not see anyone in the community going that far,  getting own cloud service up to make it easy for end users. 

Great choice of technologies btw. Last week I played with ntopng docker image on my qnap nas and it did not work since it required redis. I was shocked that all I had to do was to spin the standard redis image from docker hub, and everything started working. Looks like ntopng  auto discovered redis and got it all up and running. I did not have to configure anything anywhere.

**Comment by bucknsty** [comment]
i wish i knew how to help you out. but you made a amazing app. you dont think this will be a monthly thing do you?

**Comment by nzhome** [comment]
Why don't we just connect the smartthings smart app to the out of the box limitlessled v6 cloud server instead?  then its free? and no monthly $150USD!  thats crazy out of your own pocket.  the limitlessled wifi bridge v6 uses amazon cloud servers according to www.limitlessled.com/dev    

I have no idea how, but I'm willing to learn.   should i fork this github and give it a go?

**Comment by nzhome** [comment]
I found it under Section 5. Cloud Remote Internet access Services   www.limitlessled.com/dev

**Comment by jjensn** [comment]
Good luck! See you back here soon :-*

**Comment by jg506** [comment]
nzhome - its a fruitless exercise. Limitless API is raw sockets (LAN as well as cloud you sent above). ST does not support raw sockets so you need some sort of http to sockets translator which (in simplified manner, to the best of my understanding) what Jared has running on the cloud for us.  To have no dependency on cloud service like the one Jared's is operating we need to use a local translator (based on e.g https://www.npmjs.com/package/node-milight-promise if you like node.js) such a translator will interact with with ST using REST and with with Milight wifi bridge using sockets over LAN. A couple of examples you can look of implementation running a local translator at are Ask Alexa and homebridge-smartthings. Good luck!

**Comment by jg506** [comment]
The examples I gave above are probably not the best for this use case. A better example is device handler that interact with device using http which is then terminated in node.js using the npm mentioned above.  Example of such device handler is smartlife-rgbw-controller.groovy

**Comment by nzhome** [comment]
jg506, I think you missed my point.  LimitlessLED APi now has http, since v6.  Thats whats changed.  I will give it a go.  I am going to try and connect the smartthings smart app directly to LimitlessLED http cloud.

**Comment by jg506** [comment]
Nzhome - I did miss your point. Good luck!

**Comment by jg506** [comment]
nzhome - I'm curious, based on what have you concluded that there is http support in v6 bridge? The link you shared has only UDP and TCP examples.

**Comment by nzhome** [comment]
based on the Restful component in the link under section5. http://www.xlink.cn/products.html#overview  see diagram.  I could be wrong if they are only allowing MCU SDK component.

**Comment by jg506** [comment]
I admire your optimism. FWIW that cloud server address they provided refuse https.

**Comment by jjensn** [comment]
Even if you did get it working, do you even have a v6 bridge?

**Comment by Carterblumeyer** [comment]
Can we donate somewhere so you can run a hight cap? or donate a location that has no cap? this will get old.. Just wondering

**Comment by jjensn** [comment]
Sure, @peepers on Venmo

**Comment by jjensn** [comment]
You guys can thank @Carterblumeyer, I'm bringing up some servers now

**Comment by Carterblumeyer** [comment]
Your welcome...I will set up a monthly for you to help out... And to
support more/better development for the milight. I would ask people to give
what you can... Without us to support developers you will never get to play
with the fun toys!

**Comment by jjensn** [comment]
Just waiting on one more backend piece to finish provisioning and everything should be back up. Will update this when it's done

**Comment by jjensn** [comment]
Alright alright, I see that actions are happening on my side. Anyone want to confirm things are OK?

**Comment by shayden88** [comment]
The lights are responding now. Pretty delayed though; 3-5 seconds.

**Comment by jjensn** [comment]
I've fixed the latency issues, everything should be 100% now. Please open an issue if not.

**Comment by bucknsty** [comment]
Thanks Carter I'm tight on cash (car troubles) but I'd be willing to throw down in a week or 2 if needed. I didn't know that was a option.
