### ISSUE TITLE
smarthingsapp does not log in 

### ISSUE THREAD

**Issue by javiersrrz** [jjensn/MiThings#26]
how do you enter the smartthings app on the phone? it asks me to put in the number of the hub..but i dont have one. 

![screenshot_20161201-105329](https://cloud.githubusercontent.com/assets/24291640/20799742/6665329c-b7e3-11e6-894e-9f195ee08648.png)

**Comment by techsa573** [comment]
I'm not affiliated with the MiThings project here, but neither is this question, so I'll see if I can help.  :-)

Is this a new SmartThings hub you're trying to setup?  There should be a little paper card in the hub's box under the tray the hub was sitting on.  If you don't have the card, then you'll probably have to contact SmartThings support:  1-800-726-7864

**Comment by javiersrrz** [comment]
hi techsa573. 

maybe i explained myself incorrectly it has to do with the mithings project. I followed all instructions to be able to connect my milights with smarthings...but i understand that we dont need the smartthings hub. is this correct?

i am blocked at this stage  

"SmartThings Setup:
Load SmartThings app on phone or device
Select "Marketplace"
"SmartApps"
"My Apps"
Select "MiLight Manager" DO NOT SELECT "MITHINGS"
"Add New Hub..""

since i have to log in to the smarttings app on my phone but when i do i get prompted to add the code.

is there an older version of the smartthings app that does not ask you for the code?

**Comment by jjensn** [comment]
This is not a MiThings/MiLight problem, this is a SmartThings problem. The community forums would be the best place to ask this question
