### ISSUE TITLE
Lights are randomly and intermittently becoming unresponsive.

### ISSUE THREAD

**Issue by shayden88** [jjensn/MiThings#27]
I have a 4 milights and a led light strip connected to one mi-light hub.  Thanks to your awesome application I have all of these lights connected to my smartthings platform.  The lights are working 60% of the time probably and sometimes not responding at all for lengths of time.  I have discovered that when the lights will not respond from the smartthings app, they will still respond, and respond instantly/consistently from the mi-light app.  so the communication problem doenst seem to be between the hub and the lights.

i have also noticed that the most issues arise when trying to turn on or off all the lights with a group of lights.  For instance I recently added a google home to my setup and it works great.  But when I say turn off all first floor lights, every light and switch will respond except for the milights. Some of the milights might respond, sometimes none, and sometimes all of them, its very random.

I do not want to have to spend money on stupid overpriced Phillips hue bulbs but I also want things to work.  I would much rather donate money to you if you can get the milights working consistently.

![logs 1](https://cloud.githubusercontent.com/assets/23303357/20841369/898bba36-b881-11e6-8f31-394daec1f761.png)
![logs 2](https://cloud.githubusercontent.com/assets/23303357/20841370/898baeb0-b881-11e6-881a-545fc8423811.png)
![logs 3](https://cloud.githubusercontent.com/assets/23303357/20841368/8989a692-b881-11e6-96ad-5d4305a448a2.png)

**Comment by jjensn** [comment]
Thanks, I'll take a look if I have time this weekend

**Comment by shayden88** [comment]
Thanks.  Happy to provide any tests/information that will be useful.  And for reference the attached logs (sorry for screenshots, all I had) are from a time at the end of the night when the mi-light hub was doing one of its completely unresponsive to smartthings stints.  I was just trying to switch 1 milight on and off from the things tab of the smartthings app.  I was clicking the button and the state was changing within the app, but the light was not responding.

**Comment by shayden88** [comment]
Hey man it seems like things have been running a lot more smoothly the last couple of days. Delay is low and lights are consistently responsive. Did you make any changes? Wondering if my hub is just going out and working sometimes and not others. Ordered another one for testing.

**Comment by kellydarren** [comment]
shayden88 - I've experienced a similar issue.  However from the logs and the ST App the lights have turned on.  To overcome this issue, I have some CORE Rules set up and I basically tell ST to turn the lights on twice and off twice, this usually overcomes the fact the light isn't on, when it says it is.

**Comment by shayden88** [comment]
Kellydarren Would you mind elaborating on the CORE rules part?  I recently transferred my entire system over from Vera to smartthings and am still learning some of the more advanced features.

**Comment by kellydarren** [comment]
One of the downsides of ST is that it only caters for simple rule, ie Turn Something on or Off at set concepts.

Some members of the community decided to build an entire rules based engine ST App which should cater for anything idea you can think off.  Its currently in release candidate phase.  Here is the main link to it.  I use it for all my trigger events, ie if Motion Sensor tripped turn on Light A etc etc

https://community.smartthings.com/t/release-candidate-core-communitys-own-rule-engine/57972

**Comment by shayden88** [comment]
omg im in heaven. thanks Kellydarren.  this is exactly the kind of advanced automation I was missing after switching from Vera.

**Comment by kellydarren** [comment]
lmao..Your welcome...enjoy
