### ISSUE TITLE
Master Switch

### ISSUE THREAD

**Issue by thariqmohamed** [jjensn/MiThings#28]
Hi Jens,

Thanks for the outstanding work you have put into the app. I have followed your instructions, unfortunately everything seems to be working. The logs report no errors but within the Smartthings app, the master switch changes to unknown when you switch the other zones on or off. Please see below for a copy of the logs

HM getInitialData 0.024 (00) incidents:00, locationId:fa9507b3-6620-42e5-97b4-0081e8b1cab8
bec2ed98-3108-4b94-85c8-402060b3ccef  12:56:56 PM: debug summaryData: [[icon:indicator-dot-green, iconColor:#79b821, value:Everything OK]] - [[icon:indicator-dot-green, value:Everything OK, iconColor:#79b821]]
a53eead4-0aff-4f25-9279-779219aa232e  12:56:29 PM: debug getChildDevices(false), children=0
a53eead4-0aff-4f25-9279-779219aa232e  12:56:29 PM: info Refreshing all devices...
fb039c98-d5c1-4ee2-9692-9c4387043440  12:51:32 PM: debug getChildDevices(false), children=0
fb039c98-d5c1-4ee2-9692-9c4387043440  12:51:32 PM: info Refreshing all devices...
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:24 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@10c33687 on
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:24 PM: debug MiLight device: AC:CF:23:46:74:30, raw data from cloud: [brightness:100, result:[message:all is well, status:success], hex:#FFFFFF, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:24 PM: debug MiLight device: AC:CF:23:46:74:30, built path: rgbw/power/on/2
2c380c70-9443-4c8a-ab8a-08bbd94dd725  12:50:24 PM: debug Zone switch changed state! on!
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:22 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@7a5b9066 off
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:22 PM: debug MiLight device: AC:CF:23:46:74:30, raw data from cloud: [brightness:100, result:[message:all is well, status:success], hex:#FFFFFF, color:0, notify:[message:, title:, hasMessage:0, image:], power:off]
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:22 PM: debug MiLight device: AC:CF:23:46:74:30, built path: rgbw/power/off/2
2c380c70-9443-4c8a-ab8a-08bbd94dd725  12:50:22 PM: debug Zone switch changed state! off!
2c380c70-9443-4c8a-ab8a-08bbd94dd725  12:50:18 PM: debug Zone switch changed state! on!
2c380c70-9443-4c8a-ab8a-08bbd94dd725  12:50:18 PM: debug getChildDevices(false), children=3
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:18 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@770e5370 on
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:18 PM: debug MiLight device: AC:CF:23:46:74:30, raw data from cloud: [brightness:100, result:[message:all is well, status:success], hex:#FFFFFF, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:18 PM: debug MiLight device: AC:CF:23:46:74:30, built path: rgbw/power/on/0
2c380c70-9443-4c8a-ab8a-08bbd94dd725  12:50:18 PM: debug master switch on! AC:CF:23:46:74:30 / Master
2c380c70-9443-4c8a-ab8a-08bbd94dd725  12:50:18 PM: debug Zone switch changed state! on!
2c380c70-9443-4c8a-ab8a-08bbd94dd725  12:50:17 PM: debug Zone switch changed state! off!
2c380c70-9443-4c8a-ab8a-08bbd94dd725  12:50:17 PM: debug getChildDevices(false), children=3
973f79c7-3d1c-4526-ab2a-9d02f9471e24  12:50:17 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@42e5d563 off

**Comment by jjensn** [comment]
These bulbs do not have a "state" that is can be queried -- meaning, if you change one of the zones, the master is no longer in sync with the 4 zones.

Think of it this way, if you turn 2 zones off and leave 2 zones on, what is the state of the master switch?

**Comment by thariqmohamed** [comment]
Thanks that does make sense, didnt realise the master was acting as a switch as well. So the HUB is displayed as a master switch to turn all the bulbs off. Great tip.
