### ISSUE TITLE
Time Out Exception

### ISSUE THREAD

**Issue by kellydarren** [jjensn/MiThings#29]
Hi Jared

Didn't want to log the error here, in case its something i was doing.  But since you asked :-)

This is what i'm getting when I turn on and off a light.

22:58:28: error error: java.net.SocketTimeoutException: Read timed out
80ae3714-7f86-46d2-979d-aa4d3b9caca9  22:58:18: debug MiLight device: AC:CF:23:53:D3:8E, built path: rgbw/power/off/

Darren

**Comment by jjensn** [comment]
What's the endpoint in the code ? Not near a computer but it's in the update instructions

**Comment by kellydarren** [comment]
MiLight Manager line 84 is: https://api.mithings.pw/v1/
Milight Hub is: TCP,38899,cloud.mithings.pw

**Comment by kellydarren** [comment]
Jared 
Java error is gone. Lights are back turning on / off.
Was it something I did, and it just needed time on my end to update itself?

**Comment by jjensn** [comment]
Nope, something happened on my side. Anything socket related is on me. :(

**Comment by kellydarren** [comment]
Jared
Still all good, you can close out this issue.
