### ISSUE TITLE
Xiaomi Update

### ISSUE THREAD

**Issue by kellydarren** [jjensn/MiThings#31]
Jared
Didn't know how to contact you directly, so thought this was as good a way as any.

Looks like something has changed either in ST or Xiaomi sensors.  The lads over in this thread have the sensors connected now to ST (which are staying connected)

https://community.smartthings.com/t/xiaomi-zigbee-door-window-sensor-motion-sensor-smart-button-device-type-beta/31948/313

**Comment by jjensn** [comment]
Bad ass dude. I am going to have to see if ST got pairing worked out with their devices. Thanks man

**Comment by kellydarren** [comment]
No worries - have fun
