### ISSUE TITLE
GU10 RGB+CCT

### ISSUE THREAD

**Issue by Terellion** [jjensn/MiThings#32]
Hi,

I bought 2 of the RGB+CCT GU10 recently which i had running stand alone timed but thought i would see if they could integrate into ST.  I had a go using your device handlers and smart apps but it just wasnt working then I read in an ST thread you cant get the codes to allow you to integrate to ST, is this still the case or is it something you can sort or reverse engineer? 

If not would you recommend i use the Easybulb GU10's?

I am based in the UK.

Thanks
Paul

**Comment by jjensn** [comment]
I don't have the latest hub, so I can't develop for the new bulbs.
